.TH GIT\-TAGS "1" "2024\-05\-20" "git\-tags" "Generated Python Manual"
.SH NAME
git\-tags
.SH SYNOPSIS
.B git\-tags
[-h] [-v] [-V]
.SH DESCRIPTION
A git extension to print a detailed list of tags.

.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-version\fR
show program's version number and exit

.TP
\fB\-V\fR, \fB\-\-verbose\fR
print git command

.SH COMMENTS
Remaining options are forwarded to git. See: git help for\-each\-ref

.SH AUTHOR
.nf
Alissa Huskey <alissa.huskey@gmail.com>
.fi

.SH DISTRIBUTION
The latest version of git\-tags may be downloaded from
.UR https://github.com/alissa\-huskey/git\-tags
.UE
