#!/usr/bin/env python

from more_itertools import first
import sys

from tools import abort
from tools.config import Config
from tools.command import Command

def main():
    """Construct and execute argparse-manpage command"""

    cfg = Config()

    cmd = Command(
        module="gittags",
        author=first(cfg.get("tool", "poetry", "authors")),
        project_name=cfg.name,
        url=cfg.url,
        config=cfg,
        function="parser",
    )


    cmd.parse()

    if cmd.values.verbose:
        print(">", cmd, "\n", file=sys.stderr)

    cmd.run()

    print(f"Generated manpage at: {cmd.values.outfile}")

if __name__ == "__main__":
    main()
