#!/usr/bin/env bash

# create a new release at the current HEAD

main() {
  local message="$*" tag
  tag="v$(poetry version -s)"

  git tag -f "${tag}" ${message:+-m "$message"}
  git push ${tag}
}

main $@
